sudo: false
language: go
go:
  - 1.5.2

env:
  - "GO15VENDOREXPERIMENT=1"

before_install:
  - wget https://github.com/Masterminds/glide/releases/download/0.8.1/glide-0.8.1-linux-amd64.tar.gz
  - tar xvf glide-0.8.1-linux-amd64.tar.gz
  - mkdir -p /home/travis/gopath/bin
  - cp linux-amd64/glide /home/travis/gopath/bin && rm -rf linux-amd64

install:
  - glide update
  # - find ./vendor -name '.git' -type d | xargs rm -rf

script:
  - glide get github.com/bradfitz/iter --update-vendored
