sudo: false
language: go
go:
  - 1.5.2

before_install:
  - wget https://github.com/Masterminds/glide/releases/download/0.8.1/glide-0.8.1-linux-amd64.tar.gz
  - tar xvf glide-0.8.1-linux-amd64.tar.gz
  - cp linux-amd64/glide /home/travis/gopath/bin && rm -rf linux-amd64

script:
  - glide update
  - find ./vendor -name '.git' -type d | xargs rm -rf
  - glide get github.com/bradfitz/iter --update-vendored
